In [ ]:
import os
import requests

# 1. Definisikan IP masing-masing gateway
gateways = {
    "main": "192.168.18.14",
    "riset": "192.168.18.22"
}

# Pastikan folder logs/ lokal ada
log_dir = "datalogs"
os.makedirs(log_dir, exist_ok=True)

# 2. Proses sinkronisasi otomatis via WiFi
for name, ip in gateways.items():
    print(f"\n===== MENGHUBUNGKAN KE GATEWAY {name.upper()} ({ip}) =====")
    try:
        # A. Ambil daftar berkas CSV di MicroSD melalui endpoint /list
        list_url = f"http://{ip}/list?dir=datalog"
        response = requests.get(list_url, timeout=5)
        
        if response.status_code == 200:
            # Pecah response teks menjadi daftar nama file
            filenames = [f.strip() for f in response.text.split('\n') if f.strip().endswith('.csv')]
            print(f"Daftar file di MicroSD: {filenames}")
            
            # B. Unduh setiap berkas melalui endpoint /download
            for filename in filenames:
                # Beri akhiran nama gateway agar tidak saling menimpa
                local_name = f"{filename.replace('.csv', '')}_{name}.csv"
                local_path = os.path.join(log_dir, local_name)
                
                print(f"Mengunduh {filename} -> {local_name}...", end="")
                download_url = f"http://{ip}/download?file=/datalog/{filename}"
                file_response = requests.get(download_url, timeout=10)
                
                if file_response.status_code == 200:
                    with open(local_path, "wb") as f:
                        f.write(file_response.content)
                    print(" [Sukses]")
                else:
                    print(f" [Gagal (HTTP {file_response.status_code})]")
        else:
            print(f"Gagal memindai folder (HTTP {response.status_code})")
            
    except Exception as e:
        print(f"Koneksi gagal ke {ip} (Gateway offline atau berbeda WiFi): {e}")

print("\n===== SINKRONISASI SELESAI =====")

===== MENGHUBUNGKAN KE GATEWAY MAIN (192.168.18.14) =====
Daftar file di MicroSD: ['20260614.csv', '20260615.csv', '20260616.csv', '20260617.csv', '20260618.csv', '20260619.csv', '20260620.csv', '20260621.csv']
Mengunduh 20260614.csv -> 20260614_main.csv...

 [Sukses]
Mengunduh 20260615.csv -> 20260615_main.csv...

 [Sukses]
Mengunduh 20260616.csv -> 20260616_main.csv...

 [Sukses]
Mengunduh 20260617.csv -> 20260617_main.csv...

 [Sukses]
Mengunduh 20260618.csv -> 20260618_main.csv...

 [Sukses]
Mengunduh 20260619.csv -> 20260619_main.csv...

 [Sukses]
Mengunduh 20260620.csv -> 20260620_main.csv...

 [Sukses]
Mengunduh 20260621.csv -> 20260621_main.csv...

 [Sukses]

===== MENGHUBUNGKAN KE GATEWAY RISET (192.168.18.22) =====

Daftar file di MicroSD: ['20260614.csv', '20260615.csv', '20260616.csv', '20260617.csv', '20260618.csv', '20260619.csv', '2026-06-19.csv', '20260620.csv', '20260621.csv']
Mengunduh 20260614.csv -> 20260614_riset.csv...

 [Sukses]
Mengunduh 20260615.csv -> 20260615_riset.csv...

 [Sukses]
Mengunduh 20260616.csv -> 20260616_riset.csv...

 [Sukses]
Mengunduh 20260617.csv -> 20260617_riset.csv...

 [Sukses]
Mengunduh 20260618.csv -> 20260618_riset.csv...

 [Sukses]
Mengunduh 20260619.csv -> 20260619_riset.csv...

 [Sukses]
Mengunduh 2026-06-19.csv -> 2026-06-19_riset.csv...

 [Sukses]
Mengunduh 20260620.csv -> 20260620_riset.csv...

Koneksi gagal ke 192.168.18.22 (Gateway offline atau berbeda WiFi): HTTPConnectionPool(host='192.168.18.22', port=80): Read timed out.

===== SINKRONISASI SELESAI =====

# 1. Konfigurasi (Configuration)
Bagian ini menyimpan konfigurasi utama untuk proses migrasi. Mode `DRY_RUN` diaktifkan secara default untuk menjamin keamanan. Tidak ada unggahan ke Firebase yang akan terjadi selama `DRY_RUN = True`.

In [50]:
# KONFIGURASI UTAMA
DRY_RUN = False
BATCH_SIZE = 100

# Jalur log lokal
LOG_DIRECTORY = "d:/Github/Projek_Rainfall/Analisis_Meteorologi/datalogs"

# URL Firebase RTDB
FIREBASE_URL = "https://staklimjerukagung-default-rtdb.asia-southeast1.firebasedatabase.app/"

print(f"DRY_RUN Mode: {DRY_RUN}")
print(f"Batch Size: {BATCH_SIZE}")

DRY_RUN Mode: False
Batch Size: 100

# 2. Pemeriksaan Dependensi (Dependency Check)
Pastikan Anda mengeksekusi ini di environment conda target: `(D:\conda_env\tensorflow)` dengan menjalankan `conda activate tensorflow` di terminal PowerShell Anda. Jika dependensi belum ada, jalankan sel di bawah ini (hilangkan komentar pada baris pip install).

In [51]:
# Menyiapkan library yang dibutuhkan
import sys
import subprocess

def install_dependencies():
    packages = ["firebase-admin", "pandas", "numpy", "tqdm"]
    print("Menginstal dependensi...")
    # subprocess.check_call([sys.executable, '-m', 'pip', 'install', *packages])
    print("Silakan hilangkan komentar pada perintah di atas jika belum menginstal dependensi.")

# install_dependencies()

import os
from pathlib import Path
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
import json
print("Dependensi siap!")

Dependensi siap!

# 3. Autentikasi Firebase (Firebase Authentication)
Sel ini memuat kredensial Firebase Anda. Kami menggunakan path spesifik dari sistem Anda.

In [42]:
import firebase_admin
from firebase_admin import credentials, db

# Jangan lakukan autentikasi ganda
if not firebase_admin._apps:
    try:
        cred = credentials.Certificate('D:/staklimjerukagung-firebase-adminsdk-kcfma-e091165a9b.json')
        firebase_admin.initialize_app(cred, {
            'databaseURL': FIREBASE_URL
        })
        print("Firebase berhasil diinisialisasi!")
    except FileNotFoundError:
        print("PERINGATAN: File JSON kredensial tidak ditemukan pada path D:/staklimjerukagung-firebase-adminsdk-kcfma-e091165a9b.json. Silakan cek ulang.")
else:
    print("Firebase sudah terinisialisasi.")

Firebase sudah terinisialisasi.

# 4. Pencarian File (File Discovery)
Memindai direktori `/log` secara rekursif untuk mencari file berekstensi `.csv`, `.txt`, dan `.log` dan mengurutkannya secara kronologis.

In [52]:
def discover_files(log_dir):
    path = Path(log_dir)
    # Temukan semua file log
    extensions = ['*.csv', '*.txt', '*.log']
    file_list = []
    
    for ext in extensions:
        file_list.extend(path.rglob(ext))
        
    # Urutkan berdasarkan waktu modifikasi file
    file_list.sort(key=lambda x: x.stat().st_mtime)
    
    inventory = []
    for f in file_list:
        size_kb = f.stat().st_size / 1024
        inventory.append({
            "File": f.name,
            "Path": str(f),
            "Size (KB)": round(size_kb, 2)
        })
        
    df_inventory = pd.DataFrame(inventory)
    return file_list, df_inventory

files, df_inventory = discover_files(LOG_DIRECTORY)
print(f"Ditemukan {len(files)} file log.")
display(df_inventory.head())

Ditemukan 17 file log.

,File,Path,Size (KB)
0,20260620.csv,d:\Github\Projek_Rainfall\Analisis_Meteorologi...,207.01
1,readable_20260620.csv,d:\Github\Projek_Rainfall\Analisis_Meteorologi...,252.12
2,20260614_main.csv,d:\Github\Projek_Rainfall\Analisis_Meteorologi...,137.80
3,20260615_main.csv,d:\Github\Projek_Rainfall\Analisis_Meteorologi...,183.40
4,20260616_main.csv,d:\Github\Projek_Rainfall\Analisis_Meteorologi...,169.56

# 5. Parsing Data (Data Parsing)
Membaca file log dan memetakannya persis dengan skema `main.cpp`.
Skema Target Firebase:
```json
{
  "dew": 22.32,
  "humidity": 94.8,
  "pressure": 1009.36,
  "temperature": 23.2,
  "timestamp": 1780099969,
  "volt": 3.91,
  "rainfall": 0.0,
  "rainrate": 0.0,
  "tips": 0
}
```

In [54]:
# List penampung baris bermasalah
parsing_errors = []

# Kolom standard untuk MeteoSense CSV
STANDARD_COLUMNS = [
    'Timestamp', 'NodeID', 'NodeType', 'Temperature', 'Humidity', 
    'Pressure', 'DewPoint', 'Voltage', 'Lux', 'DsTemperature', 
    'RSSI', 'SNR', 'IsValid'
]

def parse_record(row):
    try:
        # Menghapus 'ID-' atau 'id-' dan membuang leading zeros (Misal: ID-01 -> 1)
        raw_node = str(row['NodeID']).replace('ID-', '').replace('id-', '').strip()
        station_id = int(float(raw_node))
        
        # Ekstrak field dan atasi missing value dengan null (None)
        payload = {
            "dew": float(row['DewPoint']) if pd.notna(row['DewPoint']) else None,
            "humidity": float(row['Humidity']) if pd.notna(row['Humidity']) else None,
            "pressure": float(row['Pressure']) if pd.notna(row['Pressure']) else None,
            "temperature": float(row['Temperature']) if pd.notna(row['Temperature']) else None,
            "timestamp": int(row['Timestamp']),
            "volt": float(row['Voltage']) if pd.notna(row['Voltage']) else None,
            "rainfall": 0.0,
            "rainrate": 0.0,
            "tips": 0
        }
        
        # Tambahkan Lux dan DsTemperature HANYA untuk ID-01
        if station_id == 1:
            payload["lux"] = float(row['Lux']) if pd.notna(row['Lux']) else None
            payload["soil_temp"] = float(row['DsTemperature']) if pd.notna(row['DsTemperature']) else None
            
        return station_id, payload
    except Exception as e:
        parsing_errors.append({"row_data": row.to_dict(), "error": str(e)})
        return None, None

def parse_file(file_path):
    try:
        # Cek baris pertama untuk menentukan apakah ada header
        df_first = pd.read_csv(file_path, nrows=1, header=None, on_bad_lines='skip')
        if df_first.empty:
            return []
            
        first_row_val = str(df_first.iloc[0, 0]).strip()
        
        # Jika nilai pertama di baris pertama berupa angka, maka file ini TIDAK memiliki header
        has_header = True
        if first_row_val.isdigit() or first_row_val == "nan":
            has_header = False
            
        if has_header:
            df = pd.read_csv(file_path, on_bad_lines='skip')
        else:
            print(f"-> Menggunakan kolom standar untuk file tanpa header: {os.path.basename(file_path)}")
            df = pd.read_csv(file_path, header=None, names=STANDARD_COLUMNS, on_bad_lines='skip')
            
        # Validasi ketersediaan kolom kunci
        if 'Timestamp' not in df.columns or 'NodeID' not in df.columns:
            raise ValueError(f"Kolom wajib tidak ditemukan di {file_path}")
            
        parsed_records = []
        for _, row in df.iterrows():
            st_id, payload = parse_record(row)
            if st_id is not None:
                parsed_records.append((st_id, payload))
                
        return parsed_records
    except Exception as e:
        parsing_errors.append({"file": file_path, "error": str(e)})
        return []

all_records = []
for f in tqdm(files, desc="Parsing files"):
    all_records.extend(parse_file(str(f)))
    
print(f"Berhasil parsing {len(all_records)} baris.")
print(f"Jumlah baris error: {len(parsing_errors)}")

Parsing files:   0%|          | 0/17 [00:00<?, ?it/s]

-> Menggunakan kolom standar untuk file tanpa header: 20260615_main.csv
-> Menggunakan kolom standar untuk file tanpa header: 20260615_riset.csv
Berhasil parsing 27430 baris.
Jumlah baris error: 0

# 6. Validasi Timestamp (Timestamp Validation)
Setiap record harus memiliki timestamp di atas `1700000000` (UTC unix epoch). Data yang tidak lolos akan disimpan di `invalid_records.csv`.

In [55]:
valid_records = []
invalid_timestamps = []

for st_id, payload in all_records:
    ts = payload.get("timestamp", 0)
    if ts > 1700000000:
        valid_records.append((st_id, payload))
    else:
        invalid_timestamps.append(payload)

print(f"Data valid: {len(valid_records)}")
print(f"Data invalid (dibuang): {len(invalid_timestamps)}")

if len(invalid_timestamps) > 0:
    df_inv = pd.DataFrame(invalid_timestamps)
    df_inv.to_csv("invalid_records.csv", index=False)
    print("Data invalid telah disimpan ke invalid_records.csv")

Data valid: 25330
Data invalid (dibuang): 2100
Data invalid telah disimpan ke invalid_records.csv

# 7 & 8. Audit Kronologi & Pemetaan Stasiun (Timestamp Audit & Station Mapping)
Memeriksa apakah terdapat duplikasi waktu atau interval yang terbalik untuk masing-masing `station_id`.

In [56]:
from collections import defaultdict

# Memetakan data per stasiun (Station Mapping)
station_data = defaultdict(list)
for st_id, payload in valid_records:
    station_data[st_id].append(payload)

audit_report = []

for st_id in station_data.keys():
    # Sort secara kronologis
    station_data[st_id].sort(key=lambda x: x['timestamp'])
    
    timestamps = [x['timestamp'] for x in station_data[st_id]]
    
    # Deteksi duplikat
    duplicates = len(timestamps) - len(set(timestamps))
    
    # Deteksi waktu terbalik (Seharusnya 0 karena sudah kita urutkan)
    # Namun kita catat interval yang janggal
    diffs = np.diff(timestamps)
    missing_intervals = sum(1 for d in diffs if d > 3600) # Gap lebih dari 1 jam
    
    audit_report.append({
        "Station ID": st_id,
        "Total Records": len(timestamps),
        "Duplicates": duplicates,
        "Missing Intervals (>1h)": missing_intervals,
        "Start": timestamps[0],
        "End": timestamps[-1]
    })
    
    # Filter duplikat menggunakan dict
    unique_data = {item['timestamp']: item for item in station_data[st_id]}
    station_data[st_id] = list(unique_data.values())

df_audit = pd.DataFrame(audit_report)
display(df_audit)

,Station ID,Total Records,Duplicates,Missing Intervals (>1h),Start,End
0,1,13354,4141,7,1781413035,1782005915
1,3,11976,4092,6,1781418557,1782005944

# 9. Laporan Simulasi (Dry Run Report)
Mengumpulkan hasil audit menjadi file `migration_summary.md` yang harus direview sebelum proses dilanjutkan.

In [57]:
def generate_summary():
    total_valid = sum(len(v) for v in station_data.values())
    
    report = f"""# MIGRATION SUMMARY REPORT
    
## 1. File Statistics
- **Total Files Scanned:** {len(files)}
- **Total Rows Parsed:** {len(all_records)}
- **Valid Rows for Upload:** {total_valid}
- **Invalid Rows (Rejected):** {len(invalid_timestamps)}
- **Parsing Errors:** {len(parsing_errors)}

## 2. Station Counts
"""
    for st_id, records in station_data.items():
        report += f"- **Station {st_id}:** {len(records)} records\n"
        
    report += f"""
## 3. Upload Estimates
- **Batches needed (Size {BATCH_SIZE}):** {total_valid // BATCH_SIZE + 1}
- **Estimated API Calls:** {total_valid // BATCH_SIZE + 1}

*Please execute the upload cell only after reviewing this summary.*
"""
    
    with open("migration_summary.md", "w") as f:
        f.write(report)
        
    print(report)

generate_summary()

# MIGRATION SUMMARY REPORT

## 1. File Statistics
- **Total Files Scanned:** 17
- **Total Rows Parsed:** 27430
- **Valid Rows for Upload:** 17097
- **Invalid Rows (Rejected):** 2100
- **Parsing Errors:** 0

## 2. Station Counts
- **Station 1:** 9213 records
- **Station 3:** 7884 records

## 3. Upload Estimates
- **Batches needed (Size 100):** 171
- **Estimated API Calls:** 171

*Please execute the upload cell only after reviewing this summary.*

# 10. Eksekusi Unggahan (Upload Execution)
**PERHATIAN**: Sel ini HANYA mengeksekusi unggahan jika `DRY_RUN = False`.
Data diunggah dalam ukuran batch tertentu untuk mencegah beban berlebih.
Format Path Firebase: `/auto_weather_stat/id-0{station_id}/data/{timestamp}`

In [58]:
def batch_upload():
    if DRY_RUN:
        print("MENGHENTIKAN UNGGAHAN: DRY_RUN masih aktif (True). Ubah ke False untuk mengunggah ke database.")
        return
        
    print("Memulai Migrasi ke Firebase...")
    
    for st_id, records in station_data.items():
        print(f"Mengunggah Station {st_id}...")
        
        # Batching
        for i in tqdm(range(0, len(records), BATCH_SIZE)):
            batch = records[i:i + BATCH_SIZE]
            
            # Dictionary dengan key berupa timestamp sebagai string
            update_dict = {}
            for rec in batch:
                ts = str(rec['timestamp'])
                update_dict[ts] = rec
                
            # Mendorong (Push) ke path data masing-masing station
            db.reference(f'/auto_weather_stat/id-0{st_id}/data').update(update_dict)
            
    print("Migrasi selesai!")

# JANGAN UBAH DRY_RUN SEBELUM MEMERIKSA SUMMARY REPORT
# DRY_RUN = False 
batch_upload()

Memulai Migrasi ke Firebase...
Mengunggah Station 1...

  0%|          | 0/93 [00:00<?, ?it/s]

Mengunggah Station 3...

  0%|          | 0/79 [00:00<?, ?it/s]

Migrasi selesai!

# 11. Verifikasi Pasca Unggah (Post Upload Verification)
Mengecek beberapa node sampel di Firebase untuk memverifikasi struktur schema.

In [59]:
def verify_upload():
    if DRY_RUN:
        print("Dry run aktif, tidak ada data di Firebase yang perlu diverifikasi.")
        return
        
    for st_id in station_data.keys():
        print(f"\nMengecek sample data untuk Station {st_id}...")
        # Tambahkan .order_by_key() sebelum .limit_to_last(1)
        ref = db.reference(f'/auto_weather_stat/id-0{st_id}/data').order_by_key().limit_to_last(1)
        snapshot = ref.get()
        print(json.dumps(snapshot, indent=2))

verify_upload()

Mengecek sample data untuk Station 1...
{
  "1782006240": {
    "dew": 28.18409,
    "humidity": 96.15,
    "lux": 6384.16,
    "pressure": 1010.84,
    "rainfall": 0,
    "rainrate": 0,
    "soil_temp": 25.62,
    "temperature": 28.86,
    "timestamp": 1782006240,
    "volt": 3.37
  }
}

Mengecek sample data untuk Station 3...
{
  "1782006244": {
    "dew": 25.91091,
    "humidity": 89.8,
    "pressure": 1011.69,
    "rainfall": 0,
    "rainrate": 0,
    "temperature": 27.74,
    "timestamp": 1782006244,
    "volt": 4.15
  }
}